version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    ports:
    - ${PROMETHEUS_PORT}:9090
    volumes:
    - ./docker/prometheus:/etc/prometheus
    networks:
    - shared-network
  node-exporter:
    image: prom/node-exporter:v1.1.2
    container_name: node-exporter
    ports:
    - ${NODE_EXPORTER_PORT}:9100
    networks:
    - shared-network
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    ports:
    - ${ALERTMANAGER_PORT}:9093
    privileged: true
    volumes:
    - ./docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
    - shared-network
networks:
  shared-network:
    external: true
